spring:
  application:
    name: kafka-demo


server:
  port: 9099


com:
  kafka:
    kafkaInfo:
      bootstrapServer: "localhost:9092"
      topicName: "fcm-field-event"
      stringTopicName: "fcm-field-event-string"
      groupName: "field"
      kafkaListenerContainerFactory: "kafkaListenerContainerFactory"
      groupId: "group-id-1"