spring:
  application:
    name: kafka-demo


server:
  port: 9099


com:
  kafka:
    kafkaInfo:
      bootstrapServer: "localhost:9092"
      topicName: "test-event"
      stringTopicName: "test-event-string"
      groupName: "test"
      kafkaListenerContainerFactory: "kafkaListenerContainerFactory"
      groupId: "group-id-1"